
title: Лудогорски братя
email: des@example.com
description: Hi there
destination: docs
baseurl: "" # the subpath of your site, e.g. /blog
#baseurl: "/ludogorskibratq"#
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

#
exclude:
  - docs
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
